// File generated by hand from the Firebase console config files
// (GoogleService-Info.plist / google-services.json), in the same shape
// the `flutterfire configure` CLI produces. Regenerate with that CLI if
// project settings change.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'this app only targets iOS and Android.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB18aQDelh5Cdb0TUb5bRpRHaRBlo5th-Q',
    appId: '1:71747791377:android:4c79f6e315cadec4fb9fb0',
    messagingSenderId: '71747791377',
    projectId: 'mawid-8bba0',
    storageBucket: 'mawid-8bba0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf8o5qJq3DbER8XX1pIzgdl5gCoYp_KAo',
    appId: '1:71747791377:ios:2ac29b1582bdafe0fb9fb0',
    messagingSenderId: '71747791377',
    projectId: 'mawid-8bba0',
    storageBucket: 'mawid-8bba0.firebasestorage.app',
    iosBundleId: 'com.faisalalmass.mawid',
  );
}
